version: '2'

services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - MODE=dev
    volumes:
      - ./web/:/usr/src/app/web
    command: flask run --host=0.0.0.0 --port 8000

  mongo:
    ports:
      - "27017:27017"
